name: cv_download

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  check-for-cv-update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Fetch CV from server
        run: |
          # attempt to download the CV and check if it succeeds
          if curl -L --fail -o cv.pdf "${{ secrets.CV_DOWNLOAD_URL }}"; then
            echo "CV downloaded successfully."
          else
            echo "CV download failed. Exiting silently."
            exit 0
          fi

      - name: Compare with current CV
        run: |
          # create the file incase it doesn't exist
          touch assets/CV_JUNJETTAI.pdf

          # compare and commit
          if ! cmp -s cv.pdf assets/CV_JUNJETTAI.pdf; then
            # override CV
            echo "New CV found. Updating..."
            mv cv.pdf assets/CV_JUNJETTAI.pdf

            # commit
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add assets/CV_JUNJETTAI.pdf
            git commit -m "Update CV"
            git push
          else
            echo "No updates found."
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
